[tool.poetry]
name = "petdeface"
version = "0.0.0"
description = "A nipype PET and MR defacing pipeline for BIDS datasets."
authors = ["Anthony Galassi <28850131+bendhouseart@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
scipy = "<1.9.2"
nibabel = "^5.1.0"
nipype = "^1.8.6"
pybids = "^0.16.1"
niworkflows = "^1.7.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
